- name: Wait for SSH to be reachable
  ansible.builtin.wait_for_connection:
    delay: 10
    sleep: 5
    timeout: 300

- name: Gather facts after SSH is ready
  ansible.builtin.setup:

  
- name: Test connection
  ping:

- name: Update apt cache
  apt:
    update_cache: yes

- name: Upgrade system
  apt:
    upgrade: dist

- name: Disable swap
  command: swapoff -a
  when: ansible_facts["swaptotal_mb"] > 0
